# Generated by Django 3.2.1 on 2022-04-17 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_employee', models.CharField(max_length=200, null=True)),
                ('new_department', models.CharField(max_length=200, null=True)),
                ('new_role', models.CharField(max_length=200, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('resumption_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('employee_id', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='Profile Pic.jpg', null=True, upload_to='images/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.department')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.role')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=200, null=True)),
                ('computer_make', models.CharField(max_length=200, null=True)),
                ('computer_model', models.CharField(max_length=200, null=True)),
                ('ram', models.CharField(max_length=200, null=True)),
                ('memory', models.CharField(max_length=200, null=True)),
                ('processor', models.CharField(max_length=200, null=True)),
                ('condition', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=12, null=True)),
                ('photo', models.ImageField(blank=True, default='Profile Pic.jpg', null=True, upload_to='images/')),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='computers.category')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
                ('previous_user', models.CharField(max_length=200, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.employee')),
                ('serial_no', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='computers.computer')),
            ],
        ),
    ]
